export const commands = {
    START:          'start',
    MIRRORTAR:      'india',
    MIRROR:         'america',
    MIRROR_STATUS:  'china',
    LIST:           'find',
    GET_FOLDER:     'gf',
    CANCEL_MIRROR:  'newyork',
    CANCEL_ALL:     'berlin',
    STATS:          'helsinki',
    GET_LINK:       'ilink',
    CLONE:          'tokyo',
    ID:             'germany',
    MF:             'russia',
    TAR:            'tar|t',
    UNZIP_MIRROR:   'japan',
    COUT:           'count|cnt',
    HELP:           'france',
    AUTHORIZE:      'italy',
    UNAUTHORIZE:    'paris',
    RESTART:        'restart|r',
    YTDL:           'korea'
};

export const commandsAfter: any = {
    START:          '$',
    MIRRORTAR:      '($| (.+))',
    MIRROR:         '($| (.+))',
    MIRROR_STATUS:  '$',
    LIST:           ' (.+)',
    GET_FOLDER:     '$',
    CANCEL_MIRROR:  '($| (.+))',
    CANCEL_ALL:     '$',
    STATS:          '$',
    GET_LINK:       ' (.+)',
    CLONE:          ' (.+)',
    ID:             '$',
    MF:             '$',
    TAR:            ' (.+)',
    UNZIP_MIRROR:   ' (.+)',
    COUT:           ' (.+)',
    HELP:           '$',
    AUTHORIZE:      '$',
    UNAUTHORIZE:    '$',
    RESTART:        '$',
    YTDL:           ' (.+)'
};
